# Generated by Django 4.2.15 on 2024-10-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_time'], 'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
