# Generated by Django 4.2.15 on 2024-10-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/images/1.png', upload_to='news/images/'),
        ),
    ]
