# Generated by Django 4.2.15 on 2024-10-12 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='contact',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2024, 10, 12, 6, 32, 56, 502896, tzinfo=datetime.timezone.utc)),
        ),
    ]
