# Generated by Django 4.2.15 on 2024-10-21 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_contact_options_contact_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2024, 10, 21, 6, 58, 47, 619334, tzinfo=datetime.timezone.utc)),
        ),
    ]
